# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - jesus-spring-boot

on:
  push:
    branches:
      - release
  workflow_dispatch:

env:
  APP_NAME: jesus-spring
  APP_VERSION: 0.0.1
  APP_JAR: ${APP_NAME}-${APP_VERSION}.jar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew bootJar

#      - name: rename jar deploy version
#        run: mv build/libs/${APP_JAR} build/libs/${APP_NAME}-${APP_VERSION}-${DEPLOY_VERSION}.jar

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AZURE_HOST_CREDENTIAL }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "build/libs/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
          JESUS_APP_NAME: jesus-spring
          JESUS_APP_VERSION: 0.0.1
          JESUS_APP_JAR: jesus-spring-0.0.1.jar
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            echo "hello...: ${JESUS_APP_JAR}"
            rm ${{ secrets.REMOTE_TARGET }}/latest.jar
            ln -s ${{ secrets.REMOTE_TARGET }}/${JESUS_APP_JAR} ${{ secrets.REMOTE_TARGET }}/latest.jar
            sudo systemctl restart ${JESUS_APP_NAME}.service